### ISSUE TITLE
UTF-8 support is missing

### ISSUE THREAD

**Issue by totu** [dmbaturin/soupault#1]
Building index.html with special characters does not seem to be producing correct output when using utf-8 encoding.

Input used:
```
<p>
!"#¤%&/()=?`´@£$€{[]}\~^*'öäå€½§|><
</p>
```

Output generated:
```
 !"#Â¤%&/()=?`Â´@Â£$â‚¬{[]}\~^*'Ã¶Ã¤Ã¥â‚¬Â½Â§|>< 
```

Tested with  `soupault 1.0-beta1` on Windows 10 (version 1903)

**Comment by dmbaturin** [comment]
This is interesting. In Wine and on Windows 7 it works fine for me.

Is it reproducible with any unicode strings such as "Тест кириллицы" or "漢字テスト"?

**Comment by totu** [comment]
As I was testing with the new inputs I began to doubt my setup and I had forgotten to add `<meta charset="UTF-8">` into my template and nginx was making bad assumptions. 

I will close the issue in shame.

Thanks for the help!

**Comment by dmbaturin** [comment]
Ah, cool, thanks for letting me know. I do have to admit that I gave the Windows build a rather cursory testing, so if you find anything else, let me know too.

One thing I couldn't get to work is the exec widget. On my website there's one that fetches page modification date from git log, and another one is an external index generator in Python: one fails because git somehow isn't in PATH even though it works from cmd.exe, the other fails because python complains that it can't initialize the RNG. Relative paths also don't work, as if the process doesn't inherit parent's environment.
