### ISSUE TITLE
Apply [index] on only specific index.html

### ISSUE THREAD

**Issue by misaki-m02** [dmbaturin/soupault#15]
Is ```[Index]``` apply on all index.html?

Soupault gives a warning about not finding the selector. Is there a way for limiting index to pages or sections just like ```section```, ```page```, etc. for widgets?

**Comment by dmbaturin** [comment]
Index generator will look for an element that matches `index_selector`. Setting it to a specific selector like `div#section-index` and *not including* that element in index pages where you don't want a section index is the intended way to exclude those pages.

Same approach is applicable to all widgets. For example if you have a widget like this:

```
[widgets.insert-header]
  selector = 'div#header'
  file = 'includes/header.html'
  widget = 'include'
```

it will also just not run on pages that don't have a `<div id="header">`.

That warning is there just to let you know if section index is being inserted or not. It should probably be an info level message since it can be a normal condition.

However, it may be a good point, sometimes you may not want to extract index from certain sections at all. The `[exclude_]<section|page|regex>` options should be easy to add to the indexing module.

**Comment by misaki-m02** [comment]
OK. Thank you for your response.

**Comment by dmbaturin** [comment]
The `[index]` table now has the same limiting options as widget (https://soupault.neocities.org/reference-manual/#limiting-widgets-to-pages-or-sections).

If you notice any issues with them, feel free to open an issue.
