### ISSUE TITLE
Index out of bounds error with leaf_file + sort_by in config

### ISSUE THREAD

**Issue by jchavarri** [dmbaturin/soupault#29]
I have a config that uses `index`:

```
[index]
  index = true
  dump_json = "index.json"
  sort_by = "nav_order"
  leaf_file = ".leaf"
```

I am not sure if this is relevant, but the custom field is being picked from a data attribute.

In the pages:
```
<h1 data-nav-order="2">Welcome!</h1>
```
Config:
```
[index.fields]
  nav_order = {
    selector = ["h1"],
    extract_attribute = "data-nav-order"
  }
```

It seems that at the point of dumping the index json, there is some issue that leads to an exception:

```
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at ODate.Make.From.parse_constant_i.(fun).loop in file "src/oDate.ml", line 509, characters 27-40
Called from ODate.Make.From.parse_constant_i.(fun) in file "src/oDate.ml", line 512, characters 17-23
Called from ODate.Make.From.(>>=|) in file "src/oDate.ml" (inlined), line 580, characters 6-11
Called from ODate.Make.From.generate_parser.(fun) in file "src/oDate.ml", line 724, characters 28-62
Called from ODate.Make.From.generate_parser.loop.(fun) in file "src/oDate.ml", line 735, characters 26-34
Called from ODate.Make.From.generate_parser.loop.(fun) in file "src/oDate.ml", line 735, characters 26-34
Called from ODate.Make.From.string in file "src/oDate.ml", line 763, characters 12-31
Called from Dune__exe__Utils.parse_date in file "src/utils.ml", line 242, characters 19-60
Called from Dune__exe__Autoindex.compare_entries in file "src/autoindex.ml", line 82, characters 15-25
Called from Stdlib__list.stable_sort.sort in file "list.ml", line 342, characters 19-28
Called from Stdlib__list.stable_sort in file "list.ml", line 385, characters 29-41
Called from Dune__exe__Soupault.main in file "src/soupault.ml", line 414, characters 14-51
Called from Dune__exe__Soupault in file "src/soupault.ml", line 420, characters 12-19
```

If I remove the `leaf_file` key from the config, it works fine.

Here's a small zip with a repro project for completion: 
[leaf-sort_by-bug.zip](https://github.com/dmbaturin/soupault/files/6279569/leaf-sort_by-bug.zip)

The version of soupault I'm using is 2.5.0 published in opam.

**Comment by dmbaturin** [comment]
The leaf file simply tells soupault to treat an index page as a content page. Removing it excludes it from the index extraction process, so the bug is not triggered.

The root cause is that soupault makes an assumption that the field people want to sort by is likely a date of some kind. It tries to parse the field as a date, using a list of formats (the default is `%F` (`2021-04-08`)), if it doesn't match any configured format, it resorts to lexicographic comparison. `Utils.parse_date` assumes that the only possible exception if `Failure`, but you found a string that triggers `Invalid_argument` instead... I'll fix it.

However, this brings us to a question: should we perhaps add an option to specify _how_ to sort? E.g. `index_sort_type = <"calendar" | "numeric" | "lexicographics" >`.
