### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#3]
This project looks interesting but I can't seem to get it to work.

From master, I can build the project just fine but it is unable to generate the sample site. It just copies `site/about.inc` and `site/index.inc` to `build`. If I understand correctly, soupault should be generating much more.

This might just be a problem with the sample-site because I was able to get it to do a little more for a little sample site of my own, but I couldn't widgets to work. I only tried with the `include` widget. Here's a repo with what I tried: [personal-website](https://github.com/sgpthomas/personal-website). Am I just being stupid?

I know that this is probably not enough information on it's own to figure out what's going on so let me know if I can help you figure out what is going on. I'm comfortable with ocaml.

**Comment by dmbaturin** [comment]
You are right, I've neglected the sample site and it got out of sync with reality. The cause was lack of `page_file_extensions` option in the config that is required for non-standard extensions since 1.1. 

That was done to make migration from completely hand-written sites that often store assets together with pages easier, but it also broke the sample site that I made in the very early stage of development when some design decisions weren't finalized yet.

As of non-working widgets, your issue is that you have `[widget.navbar]` instead of `[widgets.navbar]` in the config (missing "s" in "widgets"). Also, you don't want the `<html>...` wrapping in `templates/nav-menu.html`, just the HTML snippet you want to include.

I agree this is a pretty fragile config syntax, but there's a tradeoff between being able to pass arbitrary options to plugins and having a strict syntax. I think it's a good idea to add some sanity checking and warn the user about unrecognized table, perhaps offer some corrections (e.g. with ccube's Spelll). If you have ideas how to make it most user-friendly, please share.

Also, https://github.com/dmbaturin/baturin.org/ is a much more comprehensive usage example than the sample site, you may want to look into it.

**Comment by sgpthomas** [comment]
Ah so it was something silly. Thanks for helping! I'll spend some more time playing with this and then maybe help you make this more user friendly.

**Comment by dmbaturin** [comment]
I've made a pull request against your personal-website repo with a fix, too.

If you notice any more such annoyances, let me know. The downside of using my own project is that I know exactly what _not_ to do, so it's often hard to notice. ;)
