### ISSUE TITLE
widgets seem to be run on the preprocessed version of files

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#6]
I have some `.md` files that are being turning into html files but I'm getting the following error:
```
[INFO] Calling preprocessor markdown-settings/preprocess.sh on page site/blog/bril-verification.md
[INFO] Processing widget navbar on page site/blog/bril-verification.md
[INFO] Processing widget page-title on page site/blog/bril-verification.md
[INFO] Processing widget navbar-selection on page site/blog/bril-verification.md
lua: cannot convert value nil to I/O channel or html
Stack trace:
  `error' fallback (OCaml)
  main of dostring('-- Highlights the link to the current section in the menu
--...') defined in file dostring('-- Highlights the link to the current section in the menu
--...')
Lua interpreter halted with error
```
The `navbar-selection` widget works on the other pages. I did make sure that the `markdown-settings/preprocess.sh` script is working correctly.

**Comment by dmbaturin** [comment]
I tried to reproduce it using your personal-website repo, but the preprocessor fails with `Could not parse syntax definition markdown-settings/racket.xml` for me.

However, in https://github.com/sgpthomas/personal-website/blob/master/markdown-settings/markdown.template I don't see a `div#navigation`. That means the `navbar` widget would not apply to those pages because it can't find its target. Which in turn means the plugin wouldn't be able to find an element to work on (the plugin should use a check for nil and warn, of course, that's my bad).

There's now a better version of that plugin that relies on the page_url variable, so it only works with the latest code. I'll put it on the website when final 1.6 binaries are ready, but for now you can find it here: https://gist.github.com/dmbaturin/23eae3e7afe873b836dd9ceb6261d667

**Comment by sgpthomas** [comment]
Thanks! I don't know why are you getting the `racket.xml` error, maybe different version of Pandoc.

Anyways, the real problem was that something must of changed with how you decide when to apply templates. The `markdown.template` file started with `<!DOCTYPE html>` which made it not use the main soupault template.

Now I'm having problems getting the indexing working even though it was working in version 1.2. I'll keep fiddling around with it and bug you again if I get stuck. Thanks for the help!

**Comment by dmbaturin** [comment]
Since 1.5, it checks if there's an `<html>` element in the page and doesn't apply the template if there is. This is to better support sites where most or all pages are unique, so that people can use soupault as a postprocessor.

Including a complete page inside the template makes no sense anyway. However, the doctype declaration shouldn't trigger that effect, I'll check.

**Comment by dmbaturin** [comment]
Ok, so it does trigger it in practice. That's because lambdasoup tries to make that page live up to its doctype declaraction and wraps everything in `<html> <body>`. 

```
utop # Soup.parse "<!DOCTYPE html> <p>foo</p>" |> Soup.pretty_print;;
- : string =
"<html>\n <head></head>\n <body>\n  <p>\n   foo\n  </p>\n </body>\n</html>\n"
```

Since partial pages shouldn't have a doctype declaration anyway, and the behaviour of lambdasoup is sensible as far as error-tolerant HTML parsers go, I think this is in a wontfix category. I will document this behaviour of course.

**Comment by sgpthomas** [comment]
yeah this seems like the right thing to do. I wonder if there is a way to make this more obvious to debug for a user. Maybe just a message about whether it was copied into a template or not would suffice.
