### ISSUE TITLE
open up the plugin api so that it can be used with other languages

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#7]
Lua can be a little restricting and hard to debug so I propose to open up the plugin api so that you can use other languages. I think the easiest way to do this would be to allow any binary to be specified for the plugin section of the config. soupault would then use json to pass the local config keys along with the html to the binary through stdin. The binary would be expected to produce html on stdout.

**Comment by dmbaturin** [comment]
Now that #10 is merged, there's a way to run element content through an external preprocessor. Only element tag names and attributes are passed in environment variables for extra portability, rather than in JSON.

The only bit missing from your desired spec is passing custom config options to the script. Do you think it would be better to introduce as `custom_options` key that can hold an inline table, or just pass all options in their own variables like it's done for attributes?
Myself I think for this approach they may be redundant entirely since you can just include them in the `command`.

**Comment by dmbaturin** [comment]
I've been using `preprocess_element` widgets to type-check and then syntax highlight OCaml code examples, and @lthms is also doing inventive things like page revision tables extracted from git.

I believe this makes it a successful language-independent "extension API'. If anyone has specific requests though, feel free to open new issues.
