### ISSUE TITLE
support multiple authors by default for indexing

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#9]
It would be nice if the index supported multiple authors be default. I know that this is already possible at the moment with custom fields.

**Comment by dmbaturin** [comment]
It's supported actually. `index_author_selector = "#author"` is the default. Or it's not working as expected?

**Comment by sgpthomas** [comment]
this selects just the first author or if this element is a div with the authors, it returns a html element. I took a peak at the code and it looks like you use a string to store the author (in AutoIndex.ml), but I'm asking for a string list. https://github.com/sgpthomas/personal-website/blob/d07d90f708600c553ff8dd132999006137bd4b2f/soupault.conf#L72 this is what I do instead.

**Comment by dmbaturin** [comment]
Oh, I get it now. I'm not sure if there's much value in making it a built-in, since there are no built-in taxonomies anyway, so there's little difference between `<span id="author">Paul Erdos, J. Random Hacker</span>` and `<span class="author">Paul Erdos</span> <span class="author">J. Random Hacker</span>`.

The custom fields mechanism is flexible enough to accomodate that.

Unrelated, if the site online somewhere? I was thinking of adding it to https://soupault.neocities.org/users/ , your config can serve as an interesting example for new users I think, since it uses multiple features..

**Comment by sgpthomas** [comment]
yeah, [https://sgtpeacock.com](https://sgtpeacock.com). It's not really done yet but you can link it if you want.
